name: generate-develop-apk

on:
  push:
    branches:
      - develop

jobs:
  apk:
    name: Generate develop APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11
      - name: Build develop APK
        run: bash ./gradlew assembleDevelop --stacktrace
      - name: Upload develop APK
        uses: actions/upload-artifact@v1
        with:
          name: Develop APK
          path: app/build/outputs/apk/develop/app-develop.apk
