name: generate-main-apk

on:
  push:
    branches:
      - main

jobs:
  apk:
    name: Generate main APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11
      - name: Build main APK
        run: bash ./gradlew assembleMain --stacktrace
      - name: Upload main APK
        uses: actions/upload-artifact@v1
        with:
          name: Main APK
          path: app/build/outputs/apk/main/app-main.apk
